version: '3'
services:
    mysql-wcc:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=wcc
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
    api-service:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        depends_on:
          - mysql-wcc
